# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mobile Data' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mobile Data
  pod 'SnapKit'
  pod 'Charts'
  target 'Mobile DataTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Mobile DataUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end